### ISSUE TITLE
Make responsive as per the design

### ISSUE THREAD

**Issue by subrat611** [TusharSahu02/Simple-Landing-Page#1]
![image](https://user-images.githubusercontent.com/77252075/221160176-8a79900b-bbc1-4525-8830-b399b8badbc1.png)

# make this as per the design
![Landing Page — Mobile](https://user-images.githubusercontent.com/77252075/221160421-b93eacd6-f00b-4b90-9885-7ee1efc1dc3b.png)

**Comment by TusharSahu02** [comment]
Okay 👍🏻
